### PR TITLE
Geojson geodata

### PR DESCRIPTION
**Pull request by nofurtherinformation**
Summary: This PR relocates the existing geojson data from the current Linode server to an s3 compatible Cloudflare R2 bucket, and swaps the map frontend to use Geojson instead of map tiles.

Testing:

- Add this line to your .env file:
```
GEOJSON_DOMAIN=https://pub-6f2083e693164c9fb21e98181e6ab082.r2.dev/chicago-elections/geojson
```
- Build, then run the application

Details:

This PR also includes some changes to how env/metadata is passed from the build process to the frontend javascript runtime. Passing data into the nunjucks template seems more conventional than `head` properties, but there does not seem to be a great way to pass environment variables from 11ty to Solid.

This PR also dynamically adds sources on layer update rather than at build time. The reason for this is that all the geojson sources would load initially, which is like 20mb of data. 

Last, this PR includes a script to pull existing geojsons and upload them to the specific bucket, which we can use wherever the final data ends up being.

In the future, we'll want to centralize this bucket (or a bucket) as the final home for the data, and point the CSV data there, too. For now I think we can fragment the data a bit for now while we migrate stuff over and rethink storage formats.

### CODE REVIEW

**Comment by derekeder** [comment]
@nofurtherinformation nice! Chi Hack Night does not currently pay for either Cloudflare or AWS S3. Considering this data is pretty small (~20mb) and doesn't change much, any downside to committing the files to a file in the repo itself and referenced there?

**Comment by nofurtherinformation** [comment]
@derekeder Not much downside! All the standard caveats about github data storage etc etc, but this data likely won't grow that much (1mb or so per year?) -- I'll pull the data into the site's public files

**Comment by nofurtherinformation** [comment]
This PR now saves geojsons to `output/geojson`, which builds into `data/geojson/...`. I've allowlisted `output/geojson` in `gitignore`, but kept the folder ignored by default, in case there are some other data processes going on that may be bigger than we want.

**Review by derekeder — APPROVED** [review]
nice! looks great and works as it did before

**Pull request merged**
